### ISSUE TITLE
plans for adding update functionality?

### ISSUE THREAD

**Issue by fdncred** [tidwall/gjson.rs#3]
We recently integrated `gjson` into [nushell](https://github.com/nushell/nushell) via plugin. We were wondering if there were plans on providing the functionality to update based on a query string using `gjson`. Maybe that already exists and I missed it?

**Comment by tidwall** [comment]
Probably not in gjson. Gjson is designed for reading values. I made [sjson](https://github.com/tidwall/sjson) is for updating values, but there's no Rust version yet, and I have no ETA right now.

**Comment by fdncred** [comment]
ok, thanks for the heads-up. i look forward to the sjson version in rust, whenever that it.
